---
- hosts: nginx
  remote_user: root
  roles:
    - common
- hosts: node1
  remote_user: root
  roles:
    - node1
- hosts: node2
  remote_user: root
  roles:
    - node2
- hosts: node3
  remote_user: root
  roles:
    - node3
