- name: copy file
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/
    owner: root
    group: root
    mode: preserve
  with_items:
    - sites-available
    - sites-enabled
    - app.ssl.conf
    - client-size-protection.conf
    - com-protection.conf
    - ddos-protection.conf
    - dhparams.pem
    - ihcm.private.key
    - ihcm.trustchain.crt
    - ihcm.vn.chain.crt
    - l1cache-proxy-microcache.conf
    - l1cache-proxy-nocache.conf
    - l1cache-proxy-pagespeed.conf
    - l1cache-proxy.conf
    - l1cache.conf
    - lb-proxy.conf
    - lb.conf
    - mime.types
    - ngxps-ev.conf
    - ngxps-head.conf
    - ngxps-pub.conf
    - ngxps.conf
    - proxy-not-cache.conf
    - tcp-global-protection.conf
    - tickets.key
- name: create service start LB
  command: "{{ item }}"
  with_items:
    - crudini --set /lib/systemd/system/lb.service Unit Description "The service start LB"
    - crudini --set /lib/systemd/system/lb.service Unit After "syslog.target network.target remote-fs.target nss-lookup.target"
    - crudini --set /lib/systemd/system/lb.service Service Type forking
    - crudini --set /lib/systemd/system/lb.service Service "#PIDFile /var/run/lb.pid"
    - crudini --set /lib/systemd/system/lb.service Service ExecStartPre "/usr/sbin/lb -t -c /etc/nginx/lb.conf"
    - crudini --set /lib/systemd/system/lb.service Service ExecStart "/usr/sbin/lb -c /etc/nginx/lb.conf"
    - crudini --set /lib/systemd/system/lb.service Service ExecReload /bin/kill -s HUP $MAINPID
    - crudini --set /lib/systemd/system/lb.service Service ExecStop "/bin/kill -s QUIT $MAINPID"
    - crudini --set /lib/systemd/system/lb.service Service PrivateTmp true
    - crudini --set /lib/systemd/system/lb.service Install WantedBy multi-user.target
    - chmod 755 /lib/systemd/system/lb.service
- name: create service start L1cache
  command: "{{ item }}"
  with_items:
    - crudini --set /lib/systemd/system/l1cache.service Unit Description "The service start L1cache"
    - crudini --set /lib/systemd/system/l1cache.service Unit After "syslog.target network.target remote-fs.target nss-lookup.target"
    - crudini --set /lib/systemd/system/l1cache.service Service Type forking
    - crudini --set /lib/systemd/system/l1cache.service Service PIDFile /var/run/l1cache.pid
    - crudini --set /lib/systemd/system/l1cache.service Service ExecStartPre "/usr/sbin/l1cache -t -c /etc/nginx/l1cache.conf"
    - crudini --set /lib/systemd/system/l1cache.service Service ExecStart "/usr/sbin/l1cache -c /etc/nginx/l1cache.conf"
    - crudini --set /lib/systemd/system/l1cache.service Service ExecReload /bin/kill -s HUP $MAINPID
    - crudini --set /lib/systemd/system/l1cache.service Service ExecStop "/bin/kill -s QUIT $MAINPID"
    - crudini --set /lib/systemd/system/l1cache.service Service PrivateTmp true
    - crudini --set /lib/systemd/system/l1cache.service Install WantedBy multi-user.target
    - chmod 755 /lib/systemd/system/l1cache.service
- name: create forder nginx
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: "0755"
- name: copy file "/usr/sbin/nginx" -> "/usr/sbin/lb"
  shell: mv /usr/sbin/nginx /usr/sbin/lb; systemctl daemon-reload
  notify:
    - start lb
    - restart lb
- name: copy file  -> "/usr/sbin/l1cache"
  command: cp /usr/sbin/lb /usr/sbin/l1cache
  notify:
    - start l1cache
    - restart l1cache