- name: copy file
  copy:
    src: "{{ item }}"
    dest: /root/etc/nginx
  with_items:
    - sites-available
    - sites-enabled
    - client-size-protection.conf
    - gzip.conf
    - mime.types
    - modsecurity.conf
    - modsecurity_35_bad_robots.data
    - modsecurity_35_scanners.data
    - modsecurity_40_generic_attacks.data
    - modsecurity_50_outbound.data
    - modsecurity_50_outbound_malware.data
    - naxsi_core.rules
    - opt.conf
    - pagespeed-id.conf
    - pagespeed.conf
    - pagespeed.conf.nowebp
    - pagespeed.conf.old
    - proxy-not-cache.conf
    - unicode.mapping
    - waf-proxy-id.conf
    - waf-proxy-map.conf
    - waf-proxy.conf
    - waf.conf
- name: create service start LB
  command: "{{ item }}"
  with_items:
    - crudini --set /lib/systemd/system/waf.service Unit Description "The service start WAF"
    - crudini --set /lib/systemd/system/waf.service Unit After "syslog.target network.target remote-fs.target nss-lookup.target"
    - crudini --set /lib/systemd/system/waf.service Service Type forking
    - crudini --set /lib/systemd/system/waf.service Service PIDFile /run/waf.pid
    - crudini --set /lib/systemd/system/waf.service Service ExecStartPre "/usr/sbin/waf -t -c /etc/nginx/waf.conf"
    - crudini --set /lib/systemd/system/waf.service Service ExecStart "/usr/sbin/waf -c /etc/nginx/waf.conf"
    - crudini --set /lib/systemd/system/waf.service Service ExecReload /bin/kill -s HUP $MAINPID
    - crudini --set /lib/systemd/system/waf.service Service ExecStop "/bin/kill -s QUIT $MAINPID"
    - crudini --set /lib/systemd/system/waf.service Service PrivateTmp true
    - crudini --set /lib/systemd/system/waf.service Install WantedBy multi-user.target
    - chmod 755 /lib/systemd/system/waf.service
- name: create service start L1cache
  command: "{{ item }}"
  with_items:
    - crudini --set /lib/systemd/system/opt.service Unit Description "The service start opt"
    - crudini --set /lib/systemd/system/opt.service Unit After "syslog.target network.target remote-fs.target nss-lookup.target"
    - crudini --set /lib/systemd/system/opt.service Service Type forking
    - crudini --set /lib/systemd/system/opt.service Service PIDFile /run/opt.pid
    - crudini --set /lib/systemd/system/opt.service Service ExecStartPre "/usr/sbin/opt -t -c /etc/nginx/opt.conf"
    - crudini --set /lib/systemd/system/opt.service Service ExecStart "/usr/sbin/opt -c /etc/nginx/opt.conf"
    - crudini --set /lib/systemd/system/opt.service Service ExecReload /bin/kill -s HUP $MAINPID
    - crudini --set /lib/systemd/system/opt.service Service ExecStop "/bin/kill -s QUIT $MAINPID"
    - crudini --set /lib/systemd/system/opt.service Service PrivateTmp true
    - crudini --set /lib/systemd/system/opt.service Install WantedBy multi-user.target
    - chmod 755 /lib/systemd/system/opt.service

- name: create forder nginx
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: "0755"
- name: copy file "/usr/sbin/nginx" -> "/usr/sbin/lb"
  shell: mv /usr/sbin/nginx /usr/sbin/waf; systemctl daemon-reload
  notify:
    - start waf
    - restart waf
- name: copy file  -> "/usr/sbin/l1cache"
  command: cp /usr/sbin/waf /usr/sbin/opt
  notify:
    - start opt
    - restart opt